.Dd May 11, 2011
.Dt valabind \&1 "Valabind manual page"
.Os radare
.Sh NAME
.Nm valabind
.Nd vala to swig interface conversor
.Pp
.Sh SYNOPSIS
.Nm valabind
.Op Fl e
.Op Fl g
.Op Fl v
.Op Fl x
.Op Fl X
.Op Fl V Ar vapidir
.Op Fl i Ar file
.Op Fl o Ar ofile
.Op Fl m Ar modname
.Ar vapifile
.Sh DESCRIPTION
Valabind is a program written in Vala that aims to generate SWIG interfaces (.i) from a vala-generated or hand-made vapi files.
.Pp
Create bindings for many programming languages (like python, perl, ruby, lua, ..) interfacing with C or Vala code.
.Pp
Note that list of supported languages in valabind is not the same of swig.
.Pp
This is because not all swig backends are working in the same way. In other words, there are some languages that doesnt generate correct C code in some unhandled situations and depending on the vapi can break.
.Pp
Valabind can be an interesting tool for unit-testing swig and be able to find problems easily.
.
.Sh ENVIRONMENT
.Bl -tag -width Fl
.It XDG_DATA_DIRS
Standard freedesktop environment variable to point to the share prefix directory where vala looks for vapi files.
.El
.
.Sh HYPER-REFERENCES
.Bl -tag -width Fl
.It Vala 
http://live.gnome.org/Vala
.It SWIG
http://www.swig.org
.El
.
.Sh SEE ALSO
.Pp
.Xr valabind-cc(1)
.Pp
.
.Sh AUTHORS
.Pp
pancake <@nopcode.org>
