.Dd Jun 30, 2012
.Dt valabind \&1 "Valabind manual page"
.Os radare
.Sh NAME
.Nm valabind
.Nd vala to swig interface conversor
.Pp
.Sh SYNOPSIS
.Nm valabind
.Op Fl h
.Op Fl x
.Op Fl v
.Op Fl V Ar vapidir
.Op Fl o Ar ofile
.Op Fl m Ar modname
.Op Fl p Ar profile
.Op Fl N Ar namespace
.Op Fl -swig
.Op Fl -node-ffi
.Op Fl -gir
.Op Fl -cxx
.Ar vapifile
.Sh DESCRIPTION
Valabind is a program written in Vala that aims to generate nodejs, c++ or SWIG interfaces (.i) from a vala-generated or hand-made vapi files.
.Pp
SWIG opens the door to create bindings for Python, Perl, ruby, lua, and many other scripting languages.
.Pp
.Bl -tag -wdith Fl
.It Fl h
show help message
.It Fl o Ar OUTPUT
specify output file name
.It Fl m Ar NAME
specify module name
.It Fl N Ar NS
include given namespace for processing
.It Fl p Ar PROFILE
select Vala profile (posix, gobject, dova)
.It Fl x
generate c++ code for SWIG bindings
.It Fl v
show version information
.It Fl V Ar PATH
specify an alternative vapidir path
.El
.Sh ENVIRONMENT
.Bl -tag -width Fl
.It XDG_DATA_DIRS
Standard freedesktop environment variable to point to the share prefix directory where vala looks for vapi files.
.El
.
.Sh HYPER-REFERENCES
.Bl -tag -width Fl
.It Vala 
http://live.gnome.org/Vala
.It SWIG
http://www.swig.org
.El
.
.Sh SEE ALSO
.Pp
.Xr valabind-cc(1)
.Pp
.
.Sh AUTHORS
.Pp
pancake <pancake@nopcode.org>
.Pp
Eduard Burtescu <edy.burt@gmail.com>
