.Dd May 11,2011
.Dt valabind-cc \&1 "Valabind compiler frontend"
.Os valabind-cc
.Sh NAME
.
.Dd
.Nm valabind-cc
.Nd Vala to swig interface compiler
.Pp
.Sh SYNOPSIS
.Nm valabind-cc
.Ar language
.Ar modname
.Op Fl -version
.Op Fl -vapidir Ar dir
.Op Fl -glib
.Op Fl -test Ar lang
.Op Fl n
.Op Fl x
.Op Fl X
.Op Fl I Ar path
.Op Fl L Ar path
.Op Fl l Ar libname
.Op Fl C
.Ar vapifile
.Sh DESCRIPTION
valabind-cc is a frontend for valabind, swig and the C compiler (gcc by default).
.Pp
It aims to simplify the use of all the wrapped tools and compile usable bindings for many programming languages.
.Pp
.Sh EXAMPLE
valabind-cc python r_bp \-I/usr/include/r_bp r_bp.vapi
.Pp
.Sh ENVIRONMENT
.Bl -tag -width Fl
.Ar XDG_DATA_DIRS
Standard freedesktop environment variable to point to the share prefix directory where vala looks for vapi files.
.El
.Sh SEE ALSO
.Pp
.Xr valabind(1)
.Pp
.Sh AUTHORS
.Pp
pancake <@nopcode.org>
